//
// Created by Joaquin Bejar Garcia on 19/10/23.
//

#ifndef SIMPLE_COLOR_COLOR_H
#define SIMPLE_COLOR_COLOR_H

#include <string>
#include <map>

namespace simple_color {

    enum class Colors {
        AQUA = 0,
        AQUAMARINE1 = 1,
        AQUAMARINE1A = 2,
        AQUAMARINE3 = 3,
        BLACK = 4,
        BLUE1 = 5,
        BLUE3 = 6,
        BLUE3A = 7,
        BLUEVIOLET = 8,
        BLUE = 9,
        CADETBLUE = 10,
        CADETBLUEA = 11,
        CHARTREUSE1 = 12,
        CHARTREUSE2 = 13,
        CHARTREUSE2A = 14,
        CHARTREUSE3 = 15,
        CHARTREUSE3A = 16,
        CHARTREUSE4 = 17,
        CORNFLOWERBLUE = 18,
        CORNSILK1 = 19,
        CYAN1 = 20,
        CYAN2 = 21,
        CYAN = 22,
        DARKBLUE = 23,
        DARKCYAN = 24,
        DARKGOLDENROD = 25,
        DARKGREEN = 26,
        DARKKHAKI = 27,
        DARKMAGENTA = 28,
        DARKMAGENTAA = 29,
        DARKOLIVEGREEN1 = 30,
        DARKOLIVEGREEN1A = 31,
        DARKOLIVEGREEN2 = 32,
        DARKOLIVEGREEN3 = 33,
        DARKOLIVEGREEN3A = 34,
        DARKOLIVEGREEN3B = 35,
        DARKORANGE3 = 36,
        DARKORANGE3A = 37,
        DARKORANGE = 38,
        DARKRED = 39,
        DARKREDA = 40,
        DARKSEAGREEN1 = 41,
        DARKSEAGREEN1A = 42,
        DARKSEAGREEN2 = 43,
        DARKSEAGREEN2A = 44,
        DARKSEAGREEN3 = 45,
        DARKSEAGREEN3A = 46,
        DARKSEAGREEN4 = 47,
        DARKSEAGREEN4A = 48,
        DARKSEAGREEN = 49,
        DARKSLATEGRAY1 = 50,
        DARKSLATEGRAY2 = 51,
        DARKSLATEGRAY3 = 52,
        DARKTURQUOISE = 53,
        DARKVIOLET = 54,
        DARKVIOLETA = 55,
        DEEPPINK1 = 56,
        DEEPPINK1A = 57,
        DEEPPINK2 = 58,
        DEEPPINK3 = 59,
        DEEPPINK3A = 60,
        DEEPPINK4 = 61,
        DEEPPINK4A = 62,
        DEEPPINK4B = 63,
        DEEPSKYBLUE1 = 64,
        DEEPSKYBLUE2 = 65,
        DEEPSKYBLUE3 = 66,
        DEEPSKYBLUE3A = 67,
        DEEPSKYBLUE4 = 68,
        DEEPSKYBLUE4A = 69,
        DEEPSKYBLUE4B = 70,
        DODGERBLUE1 = 71,
        DODGERBLUE2 = 72,
        DODGERBLUE3 = 73,
        FUCHSIA = 74,
        GOLD1 = 75,
        GOLD3 = 76,
        GOLD3A = 77,
        GREEN1 = 78,
        GREEN3 = 79,
        GREEN3A = 80,
        GREEN4 = 81,
        GREENYELLOW = 82,
        GREEN = 83,
        GREY0 = 84,
        GREY100 = 85,
        GREY11 = 86,
        GREY15 = 87,
        GREY19 = 88,
        GREY23 = 89,
        GREY27 = 90,
        GREY30 = 91,
        GREY35 = 92,
        GREY37 = 93,
        GREY39 = 94,
        GREY3 = 95,
        GREY42 = 96,
        GREY46 = 97,
        GREY50 = 98,
        GREY53 = 99,
        GREY54 = 100,
        GREY58 = 101,
        GREY62 = 102,
        GREY63 = 103,
        GREY66 = 104,
        GREY69 = 105,
        GREY70 = 106,
        GREY74 = 107,
        GREY78 = 108,
        GREY7 = 109,
        GREY82 = 110,
        GREY84 = 111,
        GREY85 = 112,
        GREY89 = 113,
        GREY93 = 114,
        GREY = 115,
        HONEYDEW2 = 116,
        HOTPINK2 = 117,
        HOTPINK3 = 118,
        HOTPINK3A = 119,
        HOTPINK = 120,
        HOTPINKA = 121,
        INDIANRED1 = 122,
        INDIANRED1A = 123,
        INDIANRED = 124,
        INDIANREDA = 125,
        KHAKI1 = 126,
        KHAKI3 = 127,
        LIGHTCORAL = 128,
        LIGHTCYAN1 = 129,
        LIGHTCYAN3 = 130,
        LIGHTGOLDENROD1 = 131,
        LIGHTGOLDENROD2 = 132,
        LIGHTGOLDENROD2A = 133,
        LIGHTGOLDENROD2B = 134,
        LIGHTGOLDENROD3 = 135,
        LIGHTGREEN = 136,
        LIGHTGREENA = 137,
        LIGHTPINK1 = 138,
        LIGHTPINK3 = 139,
        LIGHTPINK4 = 140,
        LIGHTSALMON1 = 141,
        LIGHTSALMON3 = 142,
        LIGHTSALMON3A = 143,
        LIGHTSEAGREEN = 144,
        LIGHTSKYBLUE1 = 145,
        LIGHTSKYBLUE3 = 146,
        LIGHTSKYBLUE3A = 147,
        LIGHTSLATEBLUE = 148,
        LIGHTSLATEGREY = 149,
        LIGHTSTEELBLUE1 = 150,
        LIGHTSTEELBLUE3 = 151,
        LIGHTSTEELBLUE = 152,
        LIGHTYELLOW = 153,
        LIME = 154,
        MAGENTA = 155,
        MAGENTA1 = 156,
        MAGENTA2 = 157,
        MAGENTA3 = 158,
        MAGENTA3A = 159,
        MAGENTA3B = 160,
        MAROON = 161,
        MEDIUMORCHID1 = 162,
        MEDIUMORCHID1A = 163,
        MEDIUMORCHID3 = 164,
        MEDIUMORCHID = 165,
        MEDIUMPURPLE1 = 166,
        MEDIUMPURPLE2 = 167,
        MEDIUMPURPLE2A = 168,
        MEDIUMPURPLE3 = 169,
        MEDIUMPURPLE3A = 170,
        MEDIUMPURPLE4 = 171,
        MEDIUMPURPLE = 172,
        MEDIUMSPRINGGREEN = 173,
        MEDIUMTURQUOISE = 174,
        MEDIUMVIOLETRED = 175,
        MISTYROSE1 = 176,
        MISTYROSE3 = 177,
        NAVAJOWHITE1 = 178,
        NAVAJOWHITE3 = 179,
        NAVYBLUE = 180,
        NAVY = 181,
        OLIVE = 182,
        ORANGE = 183,
        ORANGE1 = 184,
        ORANGE2 = 185,
        ORANGE3 = 186,
        ORANGERED1 = 187,
        ORCHID1 = 188,
        ORCHID2 = 189,
        ORCHID = 190,
        PALEGREEN1 = 191,
        PALEGREEN1A = 192,
        PALEGREEN3 = 193,
        PALEGREEN3A = 194,
        PALETURQUOISE1 = 195,
        PALETURQUOISE4 = 196,
        PALEVIOLETRED1 = 197,
        PINK1 = 198,
        PINK3 = 199,
        PLUM1 = 200,
        PLUM2 = 201,
        PLUM3 = 202,
        PLUM4 = 203,
        PURPLE3 = 204,
        PURPLE4 = 205,
        PURPLE4A = 206,
        PURPLE = 207,
        PURPLEA = 208,
        PURPLEB = 209,
        RED1 = 210,
        RED3 = 211,
        RED3A = 212,
        RED = 213,
        ROSYBROWN = 214,
        ROYALBLUE1 = 215,
        SALMON1 = 216,
        SANDYBROWN = 217,
        SEAGREEN1 = 218,
        SEAGREEN1A = 219,
        SEAGREEN2 = 220,
        SEAGREEN3 = 221,
        SILVER = 222,
        SKYBLUE1 = 223,
        SKYBLUE2 = 224,
        SKYBLUE3 = 225,
        SLATEBLUE1 = 226,
        SLATEBLUE3 = 227,
        SLATEBLUE3A = 228,
        SPRINGGREEN1 = 229,
        SPRINGGREEN2 = 230,
        SPRINGGREEN2A = 231,
        SPRINGGREEN3 = 232,
        SPRINGGREEN3A = 233,
        SPRINGGREEN4 = 234,
        STEELBLUE1 = 235,
        STEELBLUE1A = 236,
        STEELBLUE3 = 237,
        STEELBLUE = 238,
        TAN = 239,
        TEAL = 240,
        THISTLE1 = 241,
        THISTLE3 = 242,
        TURQUOISE2 = 243,
        TURQUOISE4 = 244,
        VIOLET = 245,
        WHEAT1 = 246,
        WHEAT4 = 247,
        WHITE = 248,
        YELLOW1 = 249,
        YELLOW2 = 250,
        YELLOW3 = 251,
        YELLOW3A = 252,
        YELLOW4 = 253,
        YELLOW4A = 254,
        YELLOW = 255

    };


    static const std::string Normal = {0x1b, '[', '0', ';', '3', '9', 'm'};
    static const std::string Aqua = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '4', 'm'};
    static const std::string Aquamarine1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '6', 'm'};
    static const std::string Aquamarine1a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '2', 'm'};
    static const std::string Aquamarine3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '9', 'm'};
    static const std::string Black = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '0', 'm'};
    static const std::string Blue1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '1', 'm'};
    static const std::string Blue3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '9', 'm'};
    static const std::string Blue3a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '0', 'm'};
    static const std::string BlueViolet = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '7', 'm'};
    static const std::string Blue = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '2', 'm'};
    static const std::string CadetBlue = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '2', 'm'};
    static const std::string CadetBluea = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '3', 'm'};
    static const std::string Chartreuse1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '8', 'm'};
    static const std::string Chartreuse2 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '2', 'm'};
    static const std::string Chartreuse2a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '2', 'm'};
    static const std::string Chartreuse3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '0', 'm'};
    static const std::string Chartreuse3a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '6', 'm'};
    static const std::string Chartreuse4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '4', 'm'};
    static const std::string CornflowerBlue = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '9', 'm'};
    static const std::string Cornsilk1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '0', 'm'};
    static const std::string Cyan1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '1', 'm'};
    static const std::string Cyan2 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '0', 'm'};
    static const std::string Cyan = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '3', 'm'};
    static const std::string DarkBlue = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '8', 'm'};
    static const std::string DarkCyan = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '6', 'm'};
    static const std::string DarkGoldenrod = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '6', 'm'};
    static const std::string DarkGreen = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '2', 'm'};
    static const std::string DarkKhaki = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '3', 'm'};
    static const std::string DarkMagenta = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '0', 'm'};
    static const std::string DarkMagentaa = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '1', 'm'};
    static const std::string DarkOliveGreen1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '1', 'm'};
    static const std::string DarkOliveGreen1a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '2', 'm'};
    static const std::string DarkOliveGreen2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '5', 'm'};
    static const std::string DarkOliveGreen3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '7', 'm'};
    static const std::string DarkOliveGreen3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '3', 'm'};
    static const std::string DarkOliveGreen3b = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '9', 'm'};
    static const std::string DarkOrange3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '0', 'm'};
    static const std::string DarkOrange3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '6', 'm'};
    static const std::string DarkOrange = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '8', 'm'};
    static const std::string DarkRed = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '2', 'm'};
    static const std::string DarkReda = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '8', 'm'};
    static const std::string DarkSeaGreen1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '8', 'm'};
    static const std::string DarkSeaGreen1a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '3', 'm'};
    static const std::string DarkSeaGreen2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '1', 'm'};
    static const std::string DarkSeaGreen2a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '7', 'm'};
    static const std::string DarkSeaGreen3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '5', 'm'};
    static const std::string DarkSeaGreen3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '0', 'm'};
    static const std::string DarkSeaGreen4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '5', 'm'};
    static const std::string DarkSeaGreen4a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '1', 'm'};
    static const std::string DarkSeaGreen = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '8', 'm'};
    static const std::string DarkSlateGray1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '3', 'm'};
    static const std::string DarkSlateGray2 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '7', 'm'};
    static const std::string DarkSlateGray3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '6', 'm'};
    static const std::string DarkTurquoise = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '4', 'm'};
    static const std::string DarkViolet = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '2', 'm'};
    static const std::string DarkVioleta = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '8', 'm'};
    static const std::string DeepPink1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '8', 'm'};
    static const std::string DeepPink1a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '9', 'm'};
    static const std::string DeepPink2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '7', 'm'};
    static const std::string DeepPink3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '1', 'm'};
    static const std::string DeepPink3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '2', 'm'};
    static const std::string DeepPink4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '3', 'm'};
    static const std::string DeepPink4a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '9', 'm'};
    static const std::string DeepPink4b = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '5', 'm'};
    static const std::string DeepSkyBlue1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '9', 'm'};
    static const std::string DeepSkyBlue2 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '8', 'm'};
    static const std::string DeepSkyBlue3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '1', 'm'};
    static const std::string DeepSkyBlue3a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '2', 'm'};
    static const std::string DeepSkyBlue4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '3', 'm'};
    static const std::string DeepSkyBlue4a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '4', 'm'};
    static const std::string DeepSkyBlue4b = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '5', 'm'};
    static const std::string DodgerBlue1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '3', 'm'};
    static const std::string DodgerBlue2 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '7', 'm'};
    static const std::string DodgerBlue3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '6', 'm'};
    static const std::string Fuchsia = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '3', 'm'};
    static const std::string Gold1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '0', 'm'};
    static const std::string Gold3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '2', 'm'};
    static const std::string Gold3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '8', 'm'};
    static const std::string Green1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '6', 'm'};
    static const std::string Green3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '4', 'm'};
    static const std::string Green3a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '0', 'm'};
    static const std::string Green4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '8', 'm'};
    static const std::string GreenYellow = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '4', 'm'};
    static const std::string Green = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '2', 'm'};
    static const std::string Grey0 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '6', 'm'};
    static const std::string Grey100 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '1', 'm'};
    static const std::string Grey11 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '4', 'm'};
    static const std::string Grey15 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '5', 'm'};
    static const std::string Grey19 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '6', 'm'};
    static const std::string Grey23 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '7', 'm'};
    static const std::string Grey27 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '8', 'm'};
    static const std::string Grey30 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '9', 'm'};
    static const std::string Grey35 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '0', 'm'};
    static const std::string Grey37 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '9', 'm'};
    static const std::string Grey39 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '1', 'm'};
    static const std::string Grey3 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '2', 'm'};
    static const std::string Grey42 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '2', 'm'};
    static const std::string Grey46 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '3', 'm'};
    static const std::string Grey50 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '4', 'm'};
    static const std::string Grey53 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '2', 'm'};
    static const std::string Grey54 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '5', 'm'};
    static const std::string Grey58 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '6', 'm'};
    static const std::string Grey62 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '7', 'm'};
    static const std::string Grey63 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '9', 'm'};
    static const std::string Grey66 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '8', 'm'};
    static const std::string Grey69 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '5', 'm'};
    static const std::string Grey70 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '4', '9', 'm'};
    static const std::string Grey74 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '5', '0', 'm'};
    static const std::string Grey78 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '5', '1', 'm'};
    static const std::string Grey7 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '3', '3', 'm'};
    static const std::string Grey82 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '5', '2', 'm'};
    static const std::string Grey84 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '8', 'm'};
    static const std::string Grey85 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '5', '3', 'm'};
    static const std::string Grey89 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '5', '4', 'm'};
    static const std::string Grey93 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '5', '5', 'm'};
    static const std::string Grey = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '8', 'm'};
    static const std::string Honeydew2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '4', 'm'};
    static const std::string HotPink2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '9', 'm'};
    static const std::string HotPink3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '2', 'm'};
    static const std::string HotPink3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '8', 'm'};
    static const std::string HotPink = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '5', 'm'};
    static const std::string HotPinka = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '6', 'm'};
    static const std::string IndianRed1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '3', 'm'};
    static const std::string IndianRed1a = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '4', 'm'};
    static const std::string IndianRed = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '1', 'm'};
    static const std::string IndianReda = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '7', 'm'};
    static const std::string Khaki1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '8', 'm'};
    static const std::string Khaki3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '5', 'm'};
    static const std::string LightCoral = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '0', 'm'};
    static const std::string LightCyan1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '5', 'm'};
    static const std::string LightCyan3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '2', 'm'};
    static const std::string LightGoldenrod1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '7', 'm'};
    static const std::string LightGoldenrod2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '6', 'm'};
    static const std::string LightGoldenrod2a = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '1', 'm'};
    static const std::string LightGoldenrod2b = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '2', 'm'};
    static const std::string LightGoldenrod3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '9', 'm'};
    static const std::string LightGreen = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '9', 'm'};
    static const std::string LightGreena = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '0', 'm'};
    static const std::string LightPink1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '7', 'm'};
    static const std::string LightPink3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '4', 'm'};
    static const std::string LightPink4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '5', 'm'};
    static const std::string LightSalmon1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '6', 'm'};
    static const std::string LightSalmon3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '7', 'm'};
    static const std::string LightSalmon3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '3', 'm'};
    static const std::string LightSeaGreen = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '7', 'm'};
    static const std::string LightSkyBlue1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '3', 'm'};
    static const std::string LightSkyBlue3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '9', 'm'};
    static const std::string LightSkyBlue3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '0', 'm'};
    static const std::string LightSlateBlue = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '5', 'm'};
    static const std::string LightSlateGrey = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '3', 'm'};
    static const std::string LightSteelBlue1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '9', 'm'};
    static const std::string LightSteelBlue3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '6', 'm'};
    static const std::string LightSteelBlue = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '7', 'm'};
    static const std::string LightYellow = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '7', 'm'};
    static const std::string Lime = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '0', 'm'};
    static const std::string Magenta = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '1', 'm'};
    static const std::string Magenta1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '5', 'm'};
    static const std::string Magenta2 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '0', 'm'};
    static const std::string Magenta3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '7', 'm'};
    static const std::string Magenta3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '3', 'm'};
    static const std::string Magenta3b = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '4', 'm'};
    static const std::string Maroon = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '1', 'm'};
    static const std::string MediumOrchid1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '1', 'm'};
    static const std::string MediumOrchid1a = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '7', 'm'};
    static const std::string MediumOrchid3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '3', 'm'};
    static const std::string MediumOrchid = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '4', 'm'};
    static const std::string MediumPurple1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '1', 'm'};
    static const std::string MediumPurple2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '5', 'm'};
    static const std::string MediumPurple2a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '0', 'm'};
    static const std::string MediumPurple3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '7', 'm'};
    static const std::string MediumPurple3a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '8', 'm'};
    static const std::string MediumPurple4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '0', 'm'};
    static const std::string MediumPurple = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '4', 'm'};
    static const std::string MediumSpringGreen = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '9', 'm'};
    static const std::string MediumTurquoise = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '0', 'm'};
    static const std::string MediumVioletRed = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '6', 'm'};
    static const std::string MistyRose1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '4', 'm'};
    static const std::string MistyRose3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '1', 'm'};
    static const std::string NavajoWhite1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '3', 'm'};
    static const std::string NavajoWhite3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '4', 'm'};
    static const std::string NavyBlue = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '7', 'm'};
    static const std::string Navy = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '4', 'm'};
    static const std::string Olive = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '3', 'm'};
    static const std::string Orange = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '4', 'm'};
    static const std::string Orange1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '2', 'm'};
    static const std::string Orange2 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '8', 'm'};
    static const std::string Orange3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '4', 'm'};
    static const std::string OrangeRed1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '2', 'm'};
    static const std::string Orchid1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '3', 'm'};
    static const std::string Orchid2 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '2', 'm'};
    static const std::string Orchid = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '0', 'm'};
    static const std::string PaleGreen1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '1', 'm'};
    static const std::string PaleGreen1a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '6', 'm'};
    static const std::string PaleGreen3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '7', 'm'};
    static const std::string PaleGreen3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '4', 'm'};
    static const std::string PaleTurquoise1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '5', '9', 'm'};
    static const std::string PaleTurquoise4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '6', 'm'};
    static const std::string PaleVioletRed1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '1', 'm'};
    static const std::string Pink1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '8', 'm'};
    static const std::string Pink3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '5', 'm'};
    static const std::string Plum1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '9', 'm'};
    static const std::string Plum2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '3', 'm'};
    static const std::string Plum3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '6', 'm'};
    static const std::string Plum4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '6', 'm'};
    static const std::string Purple3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '6', 'm'};
    static const std::string Purple4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '4', 'm'};
    static const std::string Purple4a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '5', '5', 'm'};
    static const std::string Purple = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '5', 'm'};
    static const std::string Purplea = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '3', 'm'};
    static const std::string Purpleb = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '9', 'm'};
    static const std::string Red1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '6', 'm'};
    static const std::string Red3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '2', '4', 'm'};
    static const std::string Red3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '6', '0', 'm'};
    static const std::string Red = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '9', 'm'};
    static const std::string RosyBrown = {0x1b, '[', '3', '8', ';', '5', ';', '1', '3', '8', 'm'};
    static const std::string RoyalBlue1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '3', 'm'};
    static const std::string Salmon1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '0', '9', 'm'};
    static const std::string SandyBrown = {0x1b, '[', '3', '8', ';', '5', ';', '2', '1', '5', 'm'};
    static const std::string SeaGreen1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '4', 'm'};
    static const std::string SeaGreen1a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '5', 'm'};
    static const std::string SeaGreen2 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '3', 'm'};
    static const std::string SeaGreen3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '8', 'm'};
    static const std::string Silver = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '7', 'm'};
    static const std::string SkyBlue1 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '7', 'm'};
    static const std::string SkyBlue2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '1', '1', 'm'};
    static const std::string SkyBlue3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '4', 'm'};
    static const std::string SlateBlue1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '9', '9', 'm'};
    static const std::string SlateBlue3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '1', 'm'};
    static const std::string SlateBlue3a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '2', 'm'};
    static const std::string SpringGreen1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '8', 'm'};
    static const std::string SpringGreen2 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '2', 'm'};
    static const std::string SpringGreen2a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '7', 'm'};
    static const std::string SpringGreen3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '5', 'm'};
    static const std::string SpringGreen3a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '1', 'm'};
    static const std::string SpringGreen4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '2', '9', 'm'};
    static const std::string SteelBlue1 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '7', '5', 'm'};
    static const std::string SteelBlue1a = {0x1b, '[', '3', '8', ';', '5', ';', '0', '8', '1', 'm'};
    static const std::string SteelBlue3 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '8', 'm'};
    static const std::string SteelBlue = {0x1b, '[', '3', '8', ';', '5', ';', '0', '6', '7', 'm'};
    static const std::string Tan = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '0', 'm'};
    static const std::string Teal = {0x1b, '[', '3', '8', ';', '5', ';', '0', '0', '6', 'm'};
    static const std::string Thistle1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '5', 'm'};
    static const std::string Thistle3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '2', 'm'};
    static const std::string Turquoise2 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '4', '5', 'm'};
    static const std::string Turquoise4 = {0x1b, '[', '3', '8', ';', '5', ';', '0', '3', '0', 'm'};
    static const std::string Violet = {0x1b, '[', '3', '8', ';', '5', ';', '1', '7', '7', 'm'};
    static const std::string Wheat1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '9', 'm'};
    static const std::string Wheat4 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '1', 'm'};
    static const std::string White = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '5', 'm'};
    static const std::string Yellow1 = {0x1b, '[', '3', '8', ';', '5', ';', '2', '2', '6', 'm'};
    static const std::string Yellow2 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '9', '0', 'm'};
    static const std::string Yellow3 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '4', '8', 'm'};
    static const std::string Yellow3a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '8', '4', 'm'};
    static const std::string Yellow4 = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '0', 'm'};
    static const std::string Yellow4a = {0x1b, '[', '3', '8', ';', '5', ';', '1', '0', '6', 'm'};
    static const std::string Yellow = {0x1b, '[', '3', '8', ';', '5', ';', '0', '1', '1', 'm'};

//    std::string give_color(const Colors &color, const std::string &str);
    std::string give_color(const Colors &color, const std::string &str, bool blink = false);
}

#endif //SIMPLE_COLOR_COLOR_H
